### ISSUE TITLE
Hard coded non-translatable titles

### ISSUE THREAD

**Issue by SonniTost** [skybrud/Skybrud.Umbraco.Elements#3]
Skybrud.Umbraco.Elements/Scripts/Directives/elements.js // Edit elements & Select type
Skybrud.Umbraco.Elements/Views/Partials/Default.html // Add

Would be great if they could be translated without code alterations.

**Comment by abjerner** [comment]
Fixed in https://github.com/skybrud/Skybrud.Umbraco.Elements/releases/tag/v1.0.0-alpha016
